apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rhbk-neuroface.fullname" . }}-env
  labels:
    {{- include "rhbk-neuroface.labels" . | nindent 4 }}
data:
  NEUROFACE_API_URL: {{ include "rhbk-neuroface.neurofaceUrl" . | quote }}
  NEUROFACE_CONFIDENCE_THRESHOLD: {{ .Values.biometric.confidenceThreshold | quote }}
  NEUROFACE_MAX_ENROLLMENT_IMAGES: {{ .Values.biometric.maxEnrollmentImages | quote }}
