apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhbk-neuroface.fullname" . }}-admin
  labels:
    {{- include "rhbk-neuroface.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
