apiVersion: v1
kind: Service
metadata:
  name: {{ include "rhbk-neuroface.fullname" . }}
  labels:
    {{- include "rhbk-neuroface.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "rhbk-neuroface.selectorLabels" . | nindent 4 }}
